//
//  GetDeviceHandshake.swift
//  CovidApp - Covid Community Alert
//
//  Created by Cesar Bess on 14/04/20.
//  Copyright © 2020 Coronavirus-Herd-Immunity. All rights reserved.
//

import Foundation

extension Endpoints {

    struct PostDeviceHandshake: PostRequest, BodyRequest {
        var path: String { return "/device/handshake" }
        let body: Body
    }
}

extension Endpoints.PostDeviceHandshake {
    
    struct Body: Codable {
        /// Unique id generated by the device
        let id: String
        let device: DeviceInfo
        let os: OSInfo
        /// Google challenge string
        let challenge: String?
    }
    
    struct DeviceInfo: Codable {
        let manufacturer: String
        let model: String
    }
    
    struct OSInfo: Codable {
        let name: String
        let version: String
    }
    
    struct Response: Codable {
        let id: Int64?
        let token: String
    }
}

extension APIManager {
    static func handshakeNewDevice(googleToken: String? = nil, completion: @escaping (Result<Endpoints.PostDeviceHandshake.Response, Error>) -> Void) {
        
        let id = DeviceInfoManager.getId()
        let model = DeviceInfoManager.getModel()
        let version = DeviceInfoManager.getVersion()
        
        let request = Endpoints.PostDeviceHandshake(body: .init(id: id,
                                                                device: .init(manufacturer: "Apple", model: model),
                                                                os: .init(name: "iOS", version: version),
                                                                challenge: googleToken))
        
        executeResultRequest(request: request, completion: completion)
    }
}
